# https://github.com/vedantjain8/qdue-flask
version: '3.9'
services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_DB=flasktodoAdmin
            - POSTGRES_USER=flasktodoAdmin
            - POSTGRES_PASSWORD=flasktodoAdmin
        volumes:
            - 'qdueflask-db-data:/var/lib/postgresql/data'
        container_name: qdueflask-db
        restart: unless-stopped
    
    QDueFlask-app:
        image: ghcr.io/vedantjain8/qdue-flask:latest
        ports:
            - '7001:80'
        environment:
            - db_host=db
            - db_database=flasktodoAdmin
            - db_username=flasktodoAdmin
            - db_password=flasktodoAdmin
            - SECRET_KEY=my_secret_key
            - GUNICORN_WORKERS=2
        volumes:
            - 'qdueflask-data:/app' #optional
        container_name: qdueflask-app
        restart: unless-stopped
volumes:
  qdueflask-db-data:
  qdueflask-data: #only if you add volume in QDueFlask-app